name: CI Build

on:
  workflow_dispatch

jobs:
  build:

    strategy:
      matrix:
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: step-security/harden-runner@rc
      with:
        egress-policy: audit
    - uses: actions/checkout@v1
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.*
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.*
    - name: Build with dotnet
      run: |
        git config --global http.postBuffer 157286400
        ./build.sh --linksources=true --verbosity=verbose
      shell: bash  
